@startuml
state "design model" as designedmodel {
    state S1 
    state S2 ##[bold]green
    state S3 
    state S4 


    [*] -left-> S1
    S1 -up-> S2
    S1 -down-> S3
    S2 -down-> S4
    S3 -up-> S4
    S4 -left-> [*]
}

state mirror #lightblue{
    state "S1" as MS1 : \t**start**
    state "S2" as MS2 ##[bold]green : \t**S1 | context 1** 
    state "S3" as MS3 : \t
    state "S4" as MS4 : \t
    MS2 -down[dashed]-> MS1
}


@enduml