@startuml

state "design model" as designedmodel {
    state S1
    state S2
    state S3
    state S4


    [*] -left-> S1
    S1 -up-> S2
    S1 -down-> S3
    S2 -down-> S4
    S3 -up-> S4
    S4 -left-> [*]
}

state "mirror model" as mirror#lightblue{

    state "S1" as MS1 : \texection\n\tcontext\n\tstack
    state "S2" as MS2 : \texection\n\tcontext\n\tstack
    state "S3" as MS3 : \texection\n\tcontext\n\tstack
    state "S4" as MS4 : \texection\n\tcontext\n\tstack

}

@enduml
